version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: abril-postgres-db
    environment:
      POSTGRES_DB: abril_db
      POSTGRES_USER: abril_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network

  ws:
    build:
      context: ./ws
    container_name: ws-service
    env_file:
      - ./ws/.env
    ports:
      - "3001:3001"
    networks:
      - app-network

  front-precios:
    build:
      context: ./front-precios
    container_name: front-precios
    ports:
      - "8080:80"
    networks:
      - app-network

  front-admin:
    build:
      context: ./front-admin
    container_name: front-admin
    ports:
      - "8081:80"
    networks:
      - app-network

  portal:
    build:
      context: ./portal
    container_name: portal
    ports:
      - "8082:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
